repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        # N'exécuter bandit que sur le dossier `src/` pour éviter les faux-positifs
        # sur les fichiers de tests qui utilisent des `assert`.
        files: ^src/
        args: ["-r", "src/"]
        additional_dependencies: ["pbr"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Il est recommandé d'utiliser la dernière révision stable (v0.1.x ou plus récente)
    rev: v0.1.0
    hooks:
      # Pour le linter (ruff)
      - id: ruff
        # Placez --fix AVANT le séparateur --
        args: ["--fix", "--"]

      # Pour le formateur (ruff-format)
      - id: ruff-format
        # Le formateur applique des corrections par défaut,
        # mais on garde la structure correcte des arguments.
        # Vous pouvez laisser args vide si vous ne passez pas d'options spécifiques
        # à ruff-format.
        # Si vous vouliez passer --check ou d'autres, ils iraient avant --
        args: ["--"]
