version: '3.8'

services:
  app:
    image: python_starter_app
    build: .
    container_name: python_starter_app
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    restart: unless-stopped
    command: ["python", "src/main.py"]
